---
# plays/ci_test.yml
# list of roles to continuously test against
# .github/workflows/roles-test.yml

- name: "CI TEST"
  hosts: "{{ target | d('localhost') }}"
  become: true
  tasks:
    - name: "Display hostname"
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: "Check OS details"
      ansible.builtin.debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_architecture }})"

  roles:
    - role: "sudo"
