---
# plays/ci_test.yml
# list of roles to continuously test against
# .github/workflows/roles-test.yml

- name: "CI TEST"
  hosts: "{{ target | d('localhost')}}"
  become: yes
  roles:
    - role: "sudo"
