# .github/workflows/lint.yml
name: "Lint Ansible Roles and Playbooks"

on:
  push:
    branches:
      - '**'
    paths:
      - "roles/**"
      - "plays/**"
  pull_request:
    branches:
      - '**'
    paths:
      - "roles/**"
      - "plays/**"
  release:
    types: [created]

jobs:
  lint:
    name: "Ansible Lint and Syntax Check"
    runs-on: ubuntu-latest

    container:
      image: boxy14/ansible-ci-base-image:0.0.5

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Run ansible-playbook --syntax-check"
        run: ansible-playbook --syntax-check plays/*.yml

      - name: "Run ansible-lint roles/ plays/"
        run: ansible-lint roles/ plays/

      - name: "Run yamllint"
        run: yamllint roles/ plays/

